In [1]:
import os
import pandas as pd
import numpy as np
import dblp
from crossref.restful import Works
import requests
from serpapi import GoogleSearch

In [143]:
crossref_work = Works()

In [17]:
raw_dfs = [
    "data/cleaned/social/search-results-master-v3.csv",
]

In [141]:
# Prepare DataFrame to store the results
columns = [
    "PaperTitle",
    "DOI",
    "Authors",
    "Abstract",
    "Publisher",
    "SemanticScholarUrl",
    "DoiUrl",
    "PublicationDate",
    "FieldOfStudy",
    "Conference-Journal",
    "PublicationTypes",
    "SearchString",
    "CitationCount",
    "SearchedFrom",
]

In [142]:
sch_fields = [
    "title",
    "externalIds",
    "authors",
    "abstract",
    "url",
    "publicationDate",
    "fieldsOfStudy",
    "venue",
    "publicationTypes",
    "citationCount",
    "externalIds",
]

In [144]:
# Helpers
def extract_sch(api_url, sch_fields):
    headers = {"Content-Type": "application/json"}
    params = {
        "fields": ",".join(sch_fields),
    }
    try:
        response = requests.get(api_url, headers=headers, params=params)
        result = response.json()
        return result
    except Exception as e:
        print(e)
        return {"error": e}


def get_affiliations_google_scholar(author_name) -> list[str]:
    params = {
        "engine": "google_scholar_profiles",
        "mauthors": author_name.strip(),
        "api_key": os.environ.get("GOOGLE_SCHOLAR_API_KEY"),
    }

    try:
        search = GoogleSearch(params)
        results = search.get_dict()
        if (
            results.get("search_metadata", {}).get("status") == "Error"
            or len(results.get("profiles", [])) == 0
        ):
            return ["No Affiliation"]
        else:
            return [results["profiles"][0]["affiliations"]]
    except Exception as e:
        print(e)
        return ["No Affiliation"]


def extract_authors(sch_paper, crossref_paper):
    authors = None
    if crossref_paper is not None:
        authors = crossref_paper.get("author")
    if authors is not None:
        for i in range(len(authors)):
            author = authors[i]
            author_name = author.get("given", "") + " " + author.get("family", "")
            affiliations = author.get("affiliation", [])
            school_names = (
                [affil.get("name") for affil in affiliations]
                if affiliations != []
                else ["No Affiliation"]
            )
            # Create a new dictionary with only 'name' and 'affiliation'
            authors[i] = {
                "name": author_name.strip(),
                "affiliation": school_names,
            }
    else:
        authors = sch_paper.get("authors")
        for i in range(len(authors)):
            author = authors[i]
            affiliations = author.get("affiliations")
            if affiliations is None:
                author_name = author["name"]
                affiliations = ["No Affiliation"]

            authors[i] = {
                "name": author_name.strip(),
                "affiliation": affiliations,
            }

    return authors

In [197]:
def extract_data(row):
    pid = row["ID"]
    if "URL" in pid and "abs-" in pid:
        pid = "arXiv:" + pid.split("abs-")[1].replace("-", ".")

    api_url = f"https://api.semanticscholar.org/graph/v1/paper/{pid}"

    sch_paper = extract_sch(api_url, sch_fields)

    if sch_paper.get("error") is not None:
        # if can't search with ID, search by paper title

        api_url = f"https://api.semanticscholar.org/graph/v1/paper/search?query={row['PaperTitle']}"

        sch_paper = extract_sch(api_url, sch_fields)

        if len(sch_paper.get("data", [])) == 0:
            return {
                "PaperTitle": row["PaperTitle"],
                "DOI": pid,
                "Authors": None,
                "Abstract": None,
                "Publisher": None,
                "SemanticScholarUrl": None,
                "DoiUrl": None,
                "PublicationDate": None,
                "FieldOfStudy": None,
                "Conference-Journal": None,
                "PublicationTypes": None,
                "SearchString": row["SearchString"],
                "CitationCount": None,
                "SearchedFrom": row["SearchedFrom"],
            }
        else:
            sch_paper = sch_paper["data"][0]

    doi = sch_paper.get("externalIds", {}).get("DOI", None)

    if doi is None and str(row["ID"]).startswith("DOI"):
        doi = row["ID"].split(":")[1]

    try:
        crossref_paper = crossref_work.doi(doi)

    except Exception as e:
        crossref_paper = None

    title = row["PaperTitle"]

    authors = extract_authors(sch_paper, crossref_paper)

    abstract = sch_paper.get("abstract", None)

    sch_url = sch_paper.get("url", None)

    doi_url = f"https://doi.org/{doi}" if doi is not None else None

    publication_date = sch_paper.get("publicationDate", None)

    fields_of_study = sch_paper.get("fieldsOfStudy", [])

    venue = sch_paper.get("venue", None)

    # publisher

    if crossref_paper is not None:
        publisher = crossref_paper.get("publisher")

    elif doi and "arxiv" in doi.lower():
        publisher = "arXiv"
    else:
        publisher = None

    # paper type

    if crossref_paper is not None and crossref_paper.get("type") is not None:
        paper_type = [crossref_paper.get("type")]
    else:
        paper_type = sch_paper.get("publicationTypes", [])
        if paper_type is not None:
            paper_type = ["".join(t.split("-")).lower() for t in paper_type]

    citation_count = sch_paper.get("citationCount", None)

    # TODO: paper keywords missing

    # TODO: paper type is conference/journal for arxiv papers

    # TODO: conference-journal name mismatch with publisher, i.e., for paper with name"ChatGPT in education: A discourse analysis of worries and concerns on social media", the conference name is "International Conference on Artificial Intelligence in Education", but the publisher is "Arxiv" (becauseit queryed from arxiv), need "Springer" instead.

    new_paper = {
        "PaperTitle": title,
        "DOI": doi,
        "Authors": authors,
        "Abstract": abstract,
        "Publisher": publisher,
        "SemanticScholarUrl": sch_url,
        "DoiUrl": doi_url,
        "PublicationDate": publication_date,
        "FieldOfStudy": fields_of_study,
        "Conference-Journal": venue,
        "PublicationTypes": paper_type,
        "SearchString": row["SearchString"],
        "CitationCount": citation_count,
        "SearchedFrom": row["SearchedFrom"],
    }

    return new_paper

In [18]:
for raw_df_path in raw_dfs:
    raw_df = pd.read_csv(raw_df_path)
    total_rows = len(raw_df)
    results = []
    
    # raw_df = raw_df.iloc[2571:]

    for index, row in raw_df.iterrows():
        # if index >= 5:
        #     break
        print(f"Processing {raw_df_path}: row {index + 1}/{total_rows}...")
        paper = extract_data(row)
        results.append(paper)

    # Creating a DataFrame from the results
    results_df = pd.DataFrame(results, columns=columns)

    # Generating a new file name based on the raw data file name
    new_file_name = raw_df_path.replace(".csv", "-full.csv")
    # new_file_name = 'test.csv'

    # Saving to a CSV file
    results_df.to_csv(new_file_name, index=False)

Processing data/cleaned/social/search-results-master-v3.csv: row 1/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 2/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 3/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 4/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 5/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 6/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 7/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 8/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 9/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 10/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 11/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 12/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 13/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 14/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 15/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 16/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 17/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 18/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 19/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 20/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 21/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 22/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 23/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 24/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 25/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 26/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 27/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 28/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 29/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 30/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 31/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 32/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 33/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 34/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 35/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 36/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 37/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 38/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 39/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 40/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 41/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 42/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 43/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 44/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 45/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 46/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 47/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 48/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 49/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 50/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 51/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 52/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 53/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 54/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 55/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 56/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 57/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 58/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 59/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 60/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 61/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 62/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 63/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 64/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 65/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 66/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 67/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 68/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 69/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 70/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 71/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 72/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 73/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 74/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 75/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 76/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 77/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 78/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 79/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 80/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 81/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 82/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 83/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 84/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 85/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 86/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 87/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 88/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 89/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 90/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 91/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 92/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 93/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 94/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 95/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 96/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 97/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 98/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 99/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 100/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 101/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 102/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 103/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 104/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 105/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 106/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 107/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 108/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 109/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 110/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 111/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 112/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 113/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 114/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 115/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 116/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 117/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 118/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 119/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 120/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 121/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 122/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 123/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 124/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 125/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 126/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 127/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 128/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 129/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 130/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 131/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 132/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 133/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 134/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 135/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 136/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 137/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 138/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 139/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 140/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 141/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 142/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 143/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 144/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 145/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 146/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 147/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 148/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 149/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 150/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 151/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 152/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 153/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 154/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 155/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 156/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 157/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 158/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 159/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 160/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 161/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 162/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 163/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 164/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 165/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 166/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 167/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 168/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 169/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 170/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 171/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 172/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 173/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 174/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 175/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 176/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 177/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 178/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 179/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 180/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 181/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 182/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 183/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 184/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 185/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 186/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 187/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 188/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 189/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 190/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 191/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 192/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 193/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 194/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 195/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 196/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 197/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 198/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 199/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 200/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 201/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 202/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 203/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 204/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 205/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 206/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 207/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 208/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 209/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 210/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 211/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 212/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 213/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 214/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 215/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 216/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 217/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 218/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 219/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 220/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 221/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 222/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 223/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 224/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 225/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 226/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 227/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 228/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 229/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 230/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 231/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 232/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 233/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 234/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 235/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 236/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 237/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 238/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 239/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 240/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 241/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 242/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 243/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 244/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 245/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 246/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 247/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 248/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 249/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 250/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 251/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 252/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 253/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 254/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 255/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 256/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 257/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 258/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 259/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 260/2066...
Processing data/cleaned/social/search-results-master-v3.csv: row 261/2066...

# Post-processing stuff

In [204]:
filename = "./data/cleaned/edu/search-results-master-v3-full.csv"

In [205]:
df_clean = pd.read_csv(filename)
df_clean

,PaperTitle,DOI,Authors,Abstract,Publisher,SemanticScholarUrl,DoiUrl,PublicationDate,FieldOfStudy,Conference-Journal,PublicationTypes,SearchString,CitationCount,SearchedFrom,ID
0,Can we use ChatGPT for Mental Health and Subst...,10.2196/51243,"[{'name': 'Sophia Spallek', 'affiliation': ['N...",Background The use of generative artificial in...,NaN,https://www.semanticscholar.org/paper/083509bb...,https://doi.org/10.2196/51243,2023-07-26,['Medicine'],JMIR Medical Education,['journalarticle'],"""Generative Artificial Intelligence"" + ""misinf...",0.0,Semantic Scholar,NaN
1,Ethical implications of ChatGPT in higher educ...,10.48550/arXiv.2311.14378,"[{'name': 'Ming Li', 'affiliation': ['Northwes...",This scoping review explores the ethical chall...,arXiv,https://www.semanticscholar.org/paper/7611de3f...,https://doi.org/10.48550/arXiv.2311.14378,2023-11-24,['Computer Science'],arXiv.org,"['journalarticle', 'review']","""Generative Artificial Intelligence"" + ""misinf...",1.0,Semantic Scholar,NaN
2,Engineering Education in the Era of ChatGPT: P...,10.1109/EDUCON54358.2023.10125121,"[{'name': 'Junaid Qadir', 'affiliation': ['Pro...",Engineering education is constantly evolving t...,NaN,https://www.semanticscholar.org/paper/d553d008...,https://doi.org/10.1109/EDUCON54358.2023.10125121,2023-05-01,['Computer Science'],IEEE Global Engineering Education Conference,"['journalarticle', 'conference', 'review']","""Generative Artificial Intelligence"" + ""misinf...",154.0,Semantic Scholar,NaN
3,Developing authentic assessment through open e...,10.14742/apubs.2023.657,"[{'name': 'Mais Fatayer', 'affiliation': ['Uni...",This Pecha Kucha presentation will showcase Th...,NaN,https://www.semanticscholar.org/paper/1e0f6f05...,https://doi.org/10.14742/apubs.2023.657,2023-11-28,NaN,ASCILITE Publications,['journalarticle'],"""Generative Artificial Intelligence"" + ""access...",0.0,Semantic Scholar,NaN
4,Artificial intelligence in developing countrie...,10.1177/02666669231200628,"[{'name': 'Nishith Reddy Mannuru', 'affiliatio...",This paper explores the potential impact of Ge...,NaN,https://www.semanticscholar.org/paper/5a5e03c3...,https://doi.org/10.1177/02666669231200628,2023-09-14,NaN,Information Development,['journalarticle'],"""Generative Artificial Intelligence"" + ""access...",3.0,Semantic Scholar,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,The Covid-19 pandemic: An opportunity for refl...,10.17159/2224-7912/2020/V60N4-2A1,"[{'name': 'B. Olivier', 'affiliation': ['Penn ...","The present article poses the question, whethe...",NaN,https://www.semanticscholar.org/paper/f7362485...,https://doi.org/10.17159/2224-7912/2020/V60N4-2A1,NaN,['Political Science'],NaN,NaN,"""PaLM"" ""responsible"" ""education""",1.0,Web of Science,NaN
571,Studying the effect of AI Code Generators on S...,10.1145/3544548.3580919,"[{'name': 'Majeed Kazemitabaar', 'affiliation'...",AI code generators like OpenAI Codex have the ...,NaN,https://www.semanticscholar.org/paper/f03f39f7...,https://doi.org/10.1145/3544548.3580919,2023-02-15,['Computer Science'],International Conference on Human Factors in C...,"['journalarticle', 'book', 'conference']","""GPT-3"" ""over-reliance"" ""education""",53.0,Web of Science,NaN
572,Artificial Hallucinations by Google Bard: Thin...,10.7759/cureus.43313,"[{'name': 'Mukesh Kumar', 'affiliation': ['API...",One of the critical challenges posed by artifi...,NaN,https://www.semanticscholar.org/paper/0049f577...,https://doi.org/10.7759/cureus.43313,2023-08-01,['Medicine'],Cureus,"['journalarticle', 'editorial']","""GPT"" ""misinformation"" ""education""",4.0,Web of Science,NaN
573,Exploring the role of ChatGPT in patient care ...,10.1101/2023.06.13.23291311,"[{'name': 'R. Garg', 'affiliation': ['PostDoct...",Background ChatGPT(Chat Generative Pre-trained...,NaN,https://www.semanticscholar.org/paper/1c2a3841...,https://doi.org/10.1101/2023.06.13.23291311,2023-06-14,['Medicine'],medRxiv,"['journalarticle', 'review']","""GPT"" ""privacy"" ""education""",7.0,Web of Science,NaN
574,AN ANALYSIS OF THE MUSICAL PHILOSOPHY OF MODER...,10.24204/ejpr.2021.3844,"[{'name': 'Peifan Li', 'affiliation': ['The Un...",Three variables were considered in this study:...,NaN,https://www.semanticscholar.org/paper/2c5426a0...,https://doi.org/10.24204/ejpr.2021.3844,2022-09-10,NaN,European Journal for Philosophy of Religion,NaN,"""Claude"" ""environmental"" ""education""",2.0,Web of Science,NaN

In [206]:
# drop column 'ID'
df_clean = df_clean.drop(columns=["ID"])

In [154]:
def cast_affliation(authors):
  if authors == np.nan or type(authors) != str:
    return authors
  print(authors)
  authors = eval(authors)
  for i in range(len(authors)):
    author = dict(authors[i])
    if type(author["affiliation"]) is str:
      print(author["affiliation"])
      author["affiliation"] = [author["affiliation"]]
    authors[i] = author
  return authors

In [155]:
df_clean["Authors"] = df_clean["Authors"].apply(lambda x: cast_affliation(x))

[{'name': 'Sophia Spallek', 'affiliation': ['No Affiliation']}, {'name': 'Louise Birrell', 'affiliation': 'The Matilda Centre, The University of Sydney'}, {'name': 'Stephanie Kershaw', 'affiliation': ['No Affiliation']}, {'name': 'Emma Krogh Devine', 'affiliation': ['No Affiliation']}, {'name': 'Louise Thornton', 'affiliation': 'University of Sydney'}]
The Matilda Centre, The University of Sydney
University of Sydney
[{'name': 'Ming Li', 'affiliation': 'Northwest A & F University, China'}, {'name': 'Ariunaa Enkhtur', 'affiliation': 'Osaka University'}, {'name': 'Fei Cheng', 'affiliation': 'The Hong Kong University of Science and Technology'}, {'name': 'B. Yamamoto', 'affiliation': ''}]
Northwest A & F University, China
Osaka University
The Hong Kong University of Science and Technology

[{'name': 'Junaid Qadir', 'affiliation': ['College of Engineering, Qatar University,Department of Computer Science and Engineering,Doha,Qatar']}]
[{'name': 'Mais Fatayer', 'affiliation': 'University of Technology, Sydney'}, {'name': 'Dimity Wehr', 'affiliation': ['No Affiliation']}]
University of Technology, Sydney
[{'name': 'Nishith Reddy Mannuru', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Sakib Shahriar', 'affiliation': ['University of Guelph, Guelph, ON, Canada']}, {'name': 'Zoë A Teel', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Ting Wang', 'affiliation': ['Emporia State University, Emporia, KS, USA']}, {'name': 'Brady D Lund', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Solomon Tijani', 'affiliation': ['Nigerian Institute of Social and Economic Research, Ibadan, NG']}, {'name': 'Chalermchai Oak Pohboon', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Daniel Agbaji', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Joy Alhassan', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'JaKLyn Galley', 'affiliation': ['Emporia State University, Emporia, KS, USA']}, {'name': 'Raana Kousari', 'affiliation': ['Department of Medical Library and Information Science, School of Health Management and \rInformation Sciences, Iran University of Medical Sciences, Tehran, Iran']}, {'name': 'Lydia Ogbadu-Oladapo', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Shubham Kumar Saurav', 'affiliation': ['Documentation Research and Training Centre, Banglore, India']}, {'name': 'Aishwarya Srivastava', 'affiliation': ['Seth M.R. Jaipuria School, Rajajipuram Campus, Lucknow, India']}, {'name': 'Sai Priya Tummuru', 'affiliation': ['University of North Texas, Denton, TX, USA']}, {'name': 'Sravya Uppala', 'affiliation': ['University of North Texas, Denton, Texas, USA']}, {'name': 'Praveenkumar Vaidya', 'affiliation': ['CHRIST University Pune Lavasa India, Maharashtra, India']}]
[{'name': 'Richard McInnes', 'affiliation': 'The University of Adelaide'}, {'name': 'Mark Carandang', 'affiliation': ['No Affiliation']}, {'name': 'Ajay Kulkarni', 'affiliation': 'Engineering Manager'}]
The University of Adelaide
Engineering Manager
[{'name': 'Tom Farrelly', 'affiliation': ['School of Health & Social Sciences, Munster Technological University, V92 CX88 Tralee, Co. Kerry, Ireland']}, {'name': 'Nick Baker', 'affiliation': ['Office of Open Learning, University of Windsor, Windsor, ON N9B 3P4, Canada']}]
[{'name': 'Austin Pack', 'affiliation': ['Brigham Young University‐Hawaii  Laie Hawaii USA']}, {'name': 'Jeffrey Maloney', 'affiliation': ['Brigham Young University‐Hawaii  Laie Hawaii USA']}]
[{'name': 'Yanwei You', 'affiliation': ['School of Social Sciences, Tsinghua University, Beijing 100084, China', 'Division of Sports Science & Physical Education, Tsinghua University, Beijing 100084, China']}, {'name': 'Yuquan Chen', 'affiliation': ['Institute of Medical Information/Medical Library, Chinese Academy of Medical Sciences & Peking Union Medical College, Beijing 100020, China']}, {'name': 'Yujun You', 'affiliation': ['School of Educational Sciences, Yangzhou University, Yangzhou 225009, China']}, {'name': 'Qi Zhang', 'affiliation': ['Undergraduate Department, Taishan University, Taian 250111, China']}, {'name': 'Qiang Cao', 'affiliation': ['School of Pharmacy, Macau University of Science and Technology, Macao 999078, China']}]
[{'name': 'Shakib Sadat Shanto', 'affiliation': 'Student'}, {'name': 'Zishan Ahmed', 'affiliation': 'Associate Professor of Particle Physics and Astrophysics, Stanford University and SLAC …'}, {'name': 'Akinul Islam Jony', 'affiliation': ['No Affiliation']}]
Student
Associate Professor of Particle Physics and Astrophysics, Stanford University and SLAC …
[{'name': 'Anh Nguyen-Duc', 'affiliation': 'Professor, University of South Eastern Norway, Norwegian University of Science and'}, {'name': 'Beatriz Cabrero Daniel', 'affiliation': 'Postdoc, University of Gothenburg'}, {'name': 'Adam Przybylek', 'affiliation': 'Gdansk University of Technology'}, {'name': 'Chetan Arora', 'affiliation': 'Professor, IIT Delhi'}, {'name': 'Dron Khanna', 'affiliation': 'Research Assistant'}, {'name': 'Tomas Herda', 'affiliation': 'Konzern IT - Austrian Post'}, {'name': 'Usman Rafiq', 'affiliation': 'PhD Candidate, University of Kentucky'}, {'name': 'Jorge Melegati', 'affiliation': 'Researcher, Free University of Bozen-Bolzano'}, {'name': 'Eduardo Guerra', 'affiliation': 'Researcher, Free University of Bozen-Bolzano'}, {'name': 'Kai-Kristian Kemell', 'affiliation': 'Postdoctoral Researcher at University of Helsinki'}, {'name': 'Mika Saari', 'affiliation': 'Tampere University'}, {'name': 'Zheying Zhang', 'affiliation': 'Tampere University'}, {'name': 'Huy Le', 'affiliation': 'Professor of Management, University of Texas at San Antonio'}, {'name': 'Tho Quan', 'affiliation': ''}, {'name': 'P. Abrahamsson', 'affiliation': 'Professor of Software Engineering at Tampere University, Finland'}]
Professor, University of South Eastern Norway, Norwegian University of Science and
Postdoc, University of Gothenburg
Gdansk University of Technology
Professor, IIT Delhi
Research Assistant
Konzern IT - Austrian Post
PhD Candidate, University of Kentucky
Researcher, Free University of Bozen-Bolzano
Researcher, Free University of Bozen-Bolzano
Postdoctoral Researcher at University of Helsinki
Tampere University
Tampere University
Professor of Management, University of Texas at San Antonio

Professor of Software Engineering at Tampere University, Finland
[{'name': 'Murat Kuzlu', 'affiliation': ['Old Dominion University,Electrical Engineering Technology,Norfolk,VA,USA']}, {'name': 'Zhenxin Xiao', 'affiliation': ['The College of William and Mary,Computational Operations Research,Williamsburg,VA,USA']}, {'name': 'Salih Sarp', 'affiliation': ['Virginia Commonwealth University,Electrical and Computer Engineering,Richmond,VA,USA']}, {'name': 'Ferhat Ozgur Catak', 'affiliation': ['University of Stavanger,Department of Electrical Engineering and Computer Science,Rogaland,Norway']}, {'name': 'Necip Gurler', 'affiliation': ['eKare, Inc.,Fairfax,VA,USA']}, {'name': 'Ozgur Guler', 'affiliation': ['eKare, Inc.,Fairfax,VA,USA']}]
[{'name': 'David Baidoo-Anu', 'affiliation': "Queen's University, Canada."}, {'name': 'Leticia Owusu Ansah', 'affiliation': 'UNIVERSITY OF CAPE COAST'}]
Queen's University, Canada.
UNIVERSITY OF CAPE COAST
[{'name': 'Krzysztof Wach', 'affiliation': 'Cracow University of Economics'}, {'name': 'Cong Doanh Duong', 'affiliation': 'Assoc. Prof., National Economics University, Vietnam'}, {'name': 'Joanna Ejdys', 'affiliation': 'Professor/Białystok University of Technology, Faculty of Engineering Management'}, {'name': 'Rūta Kazlauskaitė', 'affiliation': 'ISM University of Management and Economics'}, {'name': 'Pawel Korzynski', 'affiliation': 'Associate Professor, Kozminski University / Visiting Scholar, INSEAD Business School'}, {'name': 'Grzegorz Mazurek', 'affiliation': 'Professor of Marketing, Kozminski University; Profesor Marketingu, Akademia Leona'}, {'name': 'Joanna Paliszkiewicz', 'affiliation': 'Warsaw University of Life Sciences'}, {'name': 'Ewa Ziemba', 'affiliation': 'Professor at University of Economics in Katowice / Uniwersytet Ekonomiczny w Katowicach'}]
Cracow University of Economics
Assoc. Prof., National Economics University, Vietnam
Professor/Białystok University of Technology, Faculty of Engineering Management
ISM University of Management and Economics
Associate Professor, Kozminski University / Visiting Scholar, INSEAD Business School
Professor of Marketing, Kozminski University; Profesor Marketingu, Akademia Leona
Warsaw University of Life Sciences
Professor at University of Economics in Katowice / Uniwersytet Ekonomiczny w Katowicach
[{'name': 'Sanjeev Chaand Sharma', 'affiliation': ['Department of Plastic Surgery, Leicester Royal Infirmary, Infirmary Square, Leicester, United Kingdom']}, {'name': 'Jai Parkash Ramchandani', 'affiliation': ["Faculty of Life Sciences & Medicine, King's College London, Guy's Campus, Great Maze Pond, London, United Kingdom"]}, {'name': 'Arjuna Thakker', 'affiliation': ['Academic Team of Musculoskeletal Surgery, Leicester General Hospital, University Hospitals of Leicester NHS Trust, United Kingdom']}, {'name': 'Anindya Lahiri', 'affiliation': ['Department of Plastic Surgery, Sandwell General Hospital, West Bromwich, United Kingdom']}]
[{'name': 'Hao Yu', 'affiliation': 'Associate Professor of Cognitive Psychology, Zhejiang'}, {'name': 'Yunyun Guo', 'affiliation': ['No Affiliation']}]
Associate Professor of Cognitive Psychology, Zhejiang
[{'name': 'Yunshu Ni', 'affiliation': ['Northeast Normal University']}, {'name': 'Bo Peng', 'affiliation': ['Jimei University']}, {'name': 'Siqi Yang', 'affiliation': ['Silliman University']}]
[{'name': 'Chew-Hung Chang', 'affiliation': 'National Institute of Education, Nanyang Technological Univeristy'}, {'name': 'Gillian Kidman', 'affiliation': 'A/Prof. Science Education, Monash University'}]
National Institute of Education, Nanyang Technological Univeristy
A/Prof. Science Education, Monash University
[{'name': 'Grant Cooper', 'affiliation': 'Senior Lecturer'}]
Senior Lecturer
[{'name': 'Oliver Gassmann', 'affiliation': 'University of St.Gallen'}, {'name': 'Naomi Haefner', 'affiliation': 'Assistant Professor of Technology Management, University of St. Gallen'}, {'name': 'David M. Wagner', 'affiliation': 'Professor of Biological Sciences, Northern Arizona University'}]
University of St.Gallen
Assistant Professor of Technology Management, University of St. Gallen
Professor of Biological Sciences, Northern Arizona University
[{'name': 'Carlo Schuengel', 'affiliation': ['Educational and Family Studies Vrije Universiteit Amsterdam  Amsterdam The Netherlands', 'Amsterdam Public Health Research Institute Amsterdam UMC and Vrije Universiteit Amsterdam  Amsterdam The Netherlands']}, {'name': 'Alastair van Heerden', 'affiliation': ['Center for Community Based Research Human Sciences Research Council  Pietermaritzburg South Africa', 'SAMRC/WITS Developmental Pathways for Health Research Unit, Department of Paediatrics, School of Clinical Medicine, Faculty of Health Sciences University of the Witwatersrand  Johannesburg South Africa']}]
[{'name': 'Fadel M. Megahed', 'affiliation': ['Farmer School of Business, Miami University, Oxford, Ohio']}, {'name': 'Ying-Ju Chen', 'affiliation': ['Department of Mathematics, University of Dayton, Ohio']}, {'name': 'Joshua A. Ferris', 'affiliation': ['Farmer School of Business, Miami University, Oxford, Ohio']}, {'name': 'Sven Knoth', 'affiliation': ['Department of Mathematics & Statistics, Helmut Schmidt University, Hamburg, Germany']}, {'name': 'L. Allison Jones-Farmer', 'affiliation': ['Farmer School of Business, Miami University, Oxford, Ohio']}]
[{'name': 'Tama Leaver', 'affiliation': 'Professor of Internet Studies, Curtin University'}, {'name': 'Suzanne Srdarov', 'affiliation': ['No Affiliation']}]
Professor of Internet Studies, Curtin University
[{'name': 'Lidia Marassi', 'affiliation': ['federico II napoli, Italy']}]
[{'name': 'Xiaying Li', 'affiliation': ['Division of Curriculum and Teaching, Fordham University, New York, NY 10023, USA']}, {'name': 'Belle Li', 'affiliation': ['Department of Curriculum and Instruction, Purdue University, West Lafayette, IN 47907, USA']}, {'name': 'Su-Je Cho', 'affiliation': ['Division of Curriculum and Teaching, Fordham University, New York, NY 10023, USA']}]
[{'name': 'Kevin Kuck', 'affiliation': ['George Mason University,Department of Mechanical Engineering,Fairfax,USA']}]
[{'name': 'Shunsuke Koga', 'affiliation': ['Department of Pathology and Laboratory Medicine, Hospital of the University of Pennsylvania, Philadelphia, PA, USA.']}]
[{'name': 'Kim Taylor', 'affiliation': "Assoc Prof of Media Literacy, Taylor's University and Universiti Kebangsaan Malaysia"}]
Assoc Prof of Media Literacy, Taylor's University and Universiti Kebangsaan Malaysia
[{'name': 'Sara Wilson', 'affiliation': ['Mechanical Engineering, University of Kansas, Lawrence, KS']}, {'name': 'Matthew Nishimoto', 'affiliation': ['Bioengineering, University of Kansas, Lawrence, KS']}]
[{'name': 'Christopher B. Divito', 'affiliation': ['College of Medicine, Lake Erie College of Osteopathic Medicine at Seton Hill, Greensburg, PA, USA']}, {'name': 'Bryan M. Katchikian', 'affiliation': ['College of Medicine, Lake Erie College of Osteopathic Medicine at Seton Hill, Greensburg, PA, USA']}, {'name': 'Jenna E. Gruenwald', 'affiliation': ['College of Medicine, Lake Erie College of Osteopathic Medicine at Seton Hill, Greensburg, PA, USA']}, {'name': 'Jennifer M. Burgoon', 'affiliation': ['College of Medicine, Lake Erie College of Osteopathic Medicine at Seton Hill, Greensburg, PA, USA']}]
[{'name': 'Amanda Baskwill', 'affiliation': 'Loyalist College'}]
Loyalist College
[{'name': 'Zied Bahroun', 'affiliation': ['Department of Industrial Engineering, College of Engineering, American University of Sharjah, Sharjah P.O. Box 26666, United Arab Emirates']}, {'name': 'Chiraz Anane', 'affiliation': ['Department of Foreign Languages, College of Arts, Humanities and Social Sciences, University of Sharjah, Sharjah P.O. Box 27272, United Arab Emirates']}, {'name': 'Vian Ahmed', 'affiliation': ['Department of Industrial Engineering, College of Engineering, American University of Sharjah, Sharjah P.O. Box 26666, United Arab Emirates']}, {'name': 'Andrew Zacca', 'affiliation': ['Department of Industrial Engineering, College of Engineering, American University of Sharjah, Sharjah P.O. Box 26666, United Arab Emirates']}]
[{'name': 'Zhicheng Lin', 'affiliation': ["Programme of Applied Psychology, School of Humanities and Social Science, The Chinese University of Hong Kong, Shenzhen, Guangdong 518172, People's Republic of China"]}]
[{'name': 'Niina Zuber', 'affiliation': 'Senior Research'}, {'name': 'Jan Gogoll', 'affiliation': 'Technische Universität München/ Bavarian Academy of Sciences and Humanities'}]
Senior Research
Technische Universität München/ Bavarian Academy of Sciences and Humanities
[{'name': 'Nayiri Keshishi', 'affiliation': ['No Affiliation']}, {'name': 'Dr Sarah Hack', 'affiliation': ['No Affiliation']}]
[{'name': 'Cecilia Ka Yuk Chan', 'affiliation': 'Professor, Faculty of Education, University of Hong Kong, and Founding Director of TALIC'}, {'name': 'Katherine K. W. Lee', 'affiliation': ['No Affiliation']}]
Professor, Faculty of Education, University of Hong Kong, and Founding Director of TALIC
[{'name': 'Lauren J. Woo', 'affiliation': 'Ph.D. Student, Mary Lou Fulton Teachers College, Arizona State University'}, {'name': 'Danah Henriksen', 'affiliation': 'Associate Professor of Educational Leadership and Innovation'}, {'name': 'Punya Mishra', 'affiliation': "Assoc. Dean of Scholarship & Innovation, Mary Lou Fulton Teacher's College, Arizona State"}]
Ph.D. Student, Mary Lou Fulton Teachers College, Arizona State University
Associate Professor of Educational Leadership and Innovation
Assoc. Dean of Scholarship & Innovation, Mary Lou Fulton Teacher's College, Arizona State
[{'name': 'Charles La Shure', 'affiliation': ['No Affiliation']}, {'name': '', 'affiliation': ['No Affiliation']}]
[{'name': 'Matthias Wölfel', 'affiliation': ['Faculty of Computer Science and Business Information Systems, Karlsruhe University of Applied Sciences, Moltkestr. 30, 76131 Karlsruhe, Germany', 'Faculty of Business, Economics and Social Sciences, University of Hohenheim, Schloss Hohenheim 1, 70599 Stuttgart, Germany']}, {'name': 'Mehrnoush Barani Shirzad', 'affiliation': ['Faculty of Business, Economics and Social Sciences, University of Hohenheim, Schloss Hohenheim 1, 70599 Stuttgart, Germany']}, {'name': 'Andreas Reich', 'affiliation': ['Faculty of Business, Economics and Social Sciences, University of Hohenheim, Schloss Hohenheim 1, 70599 Stuttgart, Germany']}, {'name': 'Katharina Anderer', 'affiliation': ['Faculty of Computer Science and Business Information Systems, Karlsruhe University of Applied Sciences, Moltkestr. 30, 76131 Karlsruhe, Germany', 'Faculty of Computer Science, Institut for Anthropomatics and Robotics (IAR), Karlsruher Institut for Technology (KIT), Kaiserstr. 12, 76131 Karlsruhe, Germany']}]
[{'name': 'Andrew Caines', 'affiliation': 'University of Cambridge'}, {'name': 'Luca Benedetto', 'affiliation': 'Postdoc Research Associate, University of Cambridge'}, {'name': 'Shiva Taslimipoor', 'affiliation': 'Research Associate, University of Cambridge'}, {'name': 'Christopher Davis', 'affiliation': 'Professor Comparative Ophthalmology UC, Davis'}, {'name': 'Yuan Gao', 'affiliation': 'PHD student in Electronics Engineering, University of Bristol'}, {'name': 'Oeistein Andersen', 'affiliation': ['No Affiliation']}, {'name': 'Zheng Yuan', 'affiliation': 'National Institutes of Health'}, {'name': 'Mark Elliott', 'affiliation': 'Consultant Respiratory Physician, Leeds, UK'}, {'name': 'Russell Moore', 'affiliation': 'Univeristy of Colorado'}, {'name': 'Christopher Bryant', 'affiliation': 'LS Randolph Professor of Mechanical Engineering, Virginia Tech'}, {'name': 'Marek Rei', 'affiliation': 'Lecturer, Imperial College London'}, {'name': 'H. Yannakoudakis', 'affiliation': "Lecturer, King's College London"}, {'name': 'Andrew Mullooly', 'affiliation': ['No Affiliation']}, {'name': 'D. Nicholls', 'affiliation': 'Buck Institute for Research on Aging'}, {'name': 'P. Buttery', 'affiliation': 'Research Associate - Butterfly Genetics Group (Cambridge University)'}]
University of Cambridge
Postdoc Research Associate, University of Cambridge
Research Associate, University of Cambridge
Professor Comparative Ophthalmology UC, Davis
PHD student in Electronics Engineering, University of Bristol
National Institutes of Health
Consultant Respiratory Physician, Leeds, UK
Univeristy of Colorado
LS Randolph Professor of Mechanical Engineering, Virginia Tech
Lecturer, Imperial College London
Lecturer, King's College London
Buck Institute for Research on Aging
Research Associate - Butterfly Genetics Group (Cambridge University)
[{'name': 'Benedikt Fecher', 'affiliation': 'Alexander von Humboldt Institute for Internet and Society'}, {'name': 'Marcel Hebing', 'affiliation': ['No Affiliation']}, {'name': 'M. Laufer', 'affiliation': 'CVD, University of Maryland'}, {'name': 'Jörg Pohle', 'affiliation': 'Alexander von Humboldt Institute for Internet and Society'}, {'name': 'Fabian Sofsky', 'affiliation': "Master's student, Technical University of Munich"}]
Alexander von Humboldt Institute for Internet and Society
CVD, University of Maryland
Alexander von Humboldt Institute for Internet and Society
Master's student, Technical University of Munich

In [156]:
df_clean["Authors"]

0       [{'name': 'Sophia Spallek', 'affiliation': ['N...
1       [{'name': 'Ming Li', 'affiliation': ['Northwes...
2       [{'name': 'Junaid Qadir', 'affiliation': ['Col...
3       [{'name': 'Mais Fatayer', 'affiliation': ['Uni...
4       [{'name': 'Nishith Reddy Mannuru', 'affiliatio...
                              ...
2934                                                  NaN
2935                                                  NaN
2936                                                  NaN
2937                                                  NaN
2938                                                  NaN
Name: Authors, Length: 2939, dtype: object

In [159]:
df_clean["DoiUrl"] = df_clean["DoiUrl"].apply(
    lambda x: x if x != np.nan and type(x) == str and "None" not in x else None
)

In [201]:
df_clean["PublicationTypes"] = df_clean["PublicationTypes"].apply(
    lambda x: ["".join(t.split("-")).lower() for t in eval(x)]
    if x != np.nan and type(x) == str
    else x
)

In [207]:
df_clean

,PaperTitle,DOI,Authors,Abstract,Publisher,SemanticScholarUrl,DoiUrl,PublicationDate,FieldOfStudy,Conference-Journal,PublicationTypes,SearchString,CitationCount,SearchedFrom
0,Can we use ChatGPT for Mental Health and Subst...,10.2196/51243,"[{'name': 'Sophia Spallek', 'affiliation': ['N...",Background The use of generative artificial in...,NaN,https://www.semanticscholar.org/paper/083509bb...,https://doi.org/10.2196/51243,2023-07-26,['Medicine'],JMIR Medical Education,['journalarticle'],"""Generative Artificial Intelligence"" + ""misinf...",0.0,Semantic Scholar
1,Ethical implications of ChatGPT in higher educ...,10.48550/arXiv.2311.14378,"[{'name': 'Ming Li', 'affiliation': ['Northwes...",This scoping review explores the ethical chall...,arXiv,https://www.semanticscholar.org/paper/7611de3f...,https://doi.org/10.48550/arXiv.2311.14378,2023-11-24,['Computer Science'],arXiv.org,"['journalarticle', 'review']","""Generative Artificial Intelligence"" + ""misinf...",1.0,Semantic Scholar
2,Engineering Education in the Era of ChatGPT: P...,10.1109/EDUCON54358.2023.10125121,"[{'name': 'Junaid Qadir', 'affiliation': ['Pro...",Engineering education is constantly evolving t...,NaN,https://www.semanticscholar.org/paper/d553d008...,https://doi.org/10.1109/EDUCON54358.2023.10125121,2023-05-01,['Computer Science'],IEEE Global Engineering Education Conference,"['journalarticle', 'conference', 'review']","""Generative Artificial Intelligence"" + ""misinf...",154.0,Semantic Scholar
3,Developing authentic assessment through open e...,10.14742/apubs.2023.657,"[{'name': 'Mais Fatayer', 'affiliation': ['Uni...",This Pecha Kucha presentation will showcase Th...,NaN,https://www.semanticscholar.org/paper/1e0f6f05...,https://doi.org/10.14742/apubs.2023.657,2023-11-28,NaN,ASCILITE Publications,['journalarticle'],"""Generative Artificial Intelligence"" + ""access...",0.0,Semantic Scholar
4,Artificial intelligence in developing countrie...,10.1177/02666669231200628,"[{'name': 'Nishith Reddy Mannuru', 'affiliatio...",This paper explores the potential impact of Ge...,NaN,https://www.semanticscholar.org/paper/5a5e03c3...,https://doi.org/10.1177/02666669231200628,2023-09-14,NaN,Information Development,['journalarticle'],"""Generative Artificial Intelligence"" + ""access...",3.0,Semantic Scholar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
570,The Covid-19 pandemic: An opportunity for refl...,10.17159/2224-7912/2020/V60N4-2A1,"[{'name': 'B. Olivier', 'affiliation': ['Penn ...","The present article poses the question, whethe...",NaN,https://www.semanticscholar.org/paper/f7362485...,https://doi.org/10.17159/2224-7912/2020/V60N4-2A1,NaN,['Political Science'],NaN,NaN,"""PaLM"" ""responsible"" ""education""",1.0,Web of Science
571,Studying the effect of AI Code Generators on S...,10.1145/3544548.3580919,"[{'name': 'Majeed Kazemitabaar', 'affiliation'...",AI code generators like OpenAI Codex have the ...,NaN,https://www.semanticscholar.org/paper/f03f39f7...,https://doi.org/10.1145/3544548.3580919,2023-02-15,['Computer Science'],International Conference on Human Factors in C...,"['journalarticle', 'book', 'conference']","""GPT-3"" ""over-reliance"" ""education""",53.0,Web of Science
572,Artificial Hallucinations by Google Bard: Thin...,10.7759/cureus.43313,"[{'name': 'Mukesh Kumar', 'affiliation': ['API...",One of the critical challenges posed by artifi...,NaN,https://www.semanticscholar.org/paper/0049f577...,https://doi.org/10.7759/cureus.43313,2023-08-01,['Medicine'],Cureus,"['journalarticle', 'editorial']","""GPT"" ""misinformation"" ""education""",4.0,Web of Science
573,Exploring the role of ChatGPT in patient care ...,10.1101/2023.06.13.23291311,"[{'name': 'R. Garg', 'affiliation': ['PostDoct...",Background ChatGPT(Chat Generative Pre-trained...,NaN,https://www.semanticscholar.org/paper/1c2a3841...,https://doi.org/10.1101/2023.06.13.23291311,2023-06-14,['Medicine'],medRxiv,"['journalarticle', 'review']","""GPT"" ""privacy"" ""education""",7.0,Web of Science
574,AN ANALYSIS OF THE MUSICAL PHILOSOPHY OF MODER...,10.24204/ejpr.2021.3844,"[{'name': 'Peifan Li', 'affiliation': ['The Un...",Three variables were considered in this study:...,NaN,https://www.semanticscholar.org/paper/2c5426a0...,https://doi.org/10.24204/ejpr.2021.3844,2022-09-10,NaN,European Journal for Philosophy of Religion,NaN,"""Claude"" ""environmental"" ""education""",2.0,Web of Science

In [209]:
df_raw = pd.read_csv("./data/cleaned/social/search-results-master-v2.csv")
df_clean = pd.read_csv("./data/cleaned/social/search-results-master-v2-full.csv")

In [208]:
df_clean.to_csv(filename, index=False)

In [214]:
pd.merge(df_raw, df_clean, on=["PaperTitle", "SearchString", "SearchedFrom"], how="left").drop_duplicates(subset=["PaperTitle"], keep="last").to_csv("./data/cleaned/social/search-results-master-v2-full.csv", index=False)

# Testing stuff

In [37]:
len(results)

179

In [14]:
api_url = "https://api.semanticscholar.org/graph/v1/paper/search/"
headers = {
    "Content-Type": "application/json",
    "x-api-key": "X48LIBLqr86ouHlnMYd3z052sgEm3Nd2wMORPzu5",
}
fields = ["title", "externalIds", "paperId", "url"]
sch_search_string = "Saving the Vicuna: The Political, Biophysical, and Cultural History of Wild Animal Conservation in Peru, 1964-2000"
params = {"query": sch_search_string, "year": "2019-", "fields": ",".join(fields)}
response = requests.get(api_url, headers=headers, params=params)
result = response.json()
print(result)

{'total': 1, 'offset': 0, 'data': [{'paperId': '64fa0be92833e344e79f205976fb77a489461a58', 'externalIds': {'MAG': '3005763097', 'DOI': '10.1093/ahr/rhz939', 'CorpusId': 213377959}, 'url': 'https://www.semanticscholar.org/paper/64fa0be92833e344e79f205976fb77a489461a58', 'title': 'Saving the Vicuña: The Political, Biophysical, and Cultural History of Wild Animal Conservation in Peru, 1964–2000'}]}

In [12]:
pid = "ArXiv:2205.07144"
api_url = f"https://api.semanticscholar.org/graph/v1/paper/{pid}"
sch_paper = extract_sch(api_url, sch_fields)
sch_paper

{'paperId': 'cb179c916e73c7a6b0edf973b4ed087fe6224722',
 'externalIds': {'DBLP': 'conf/nips/LiBY22',
  'ArXiv': '2205.07144',
  'CorpusId': 248811155},
 'url': 'https://www.semanticscholar.org/paper/cb179c916e73c7a6b0edf973b4ed087fe6224722',
 'title': 'Network change point localisation under local differential privacy',
 'abstract': 'Network data are ubiquitous in our daily life, containing rich but often sensitive information. In this paper, we expand the current static analysis of privatised networks to a dynamic framework by considering a sequence of networks with potential change points. We investigate the fundamental limits in consistently localising change points under both node and edge privacy constraints, demonstrating interesting phase transition in terms of the signal-to-noise ratio condition, accompanied by polynomial-time algorithms. The private signal-to-noise ratio conditions quantify the costs of the privacy for change point localisation problems and exhibit a different scaling in the sparsity parameter compared to the non-private counterparts. Our algorithms are shown to be optimal under the edge LDP constraint up to log factors. Under node LDP constraint, a gap exists between our upper bound and lower bound and we leave it as an interesting open problem.',
 'venue': 'Neural Information Processing Systems',
 'citationCount': 4,
 'fieldsOfStudy': ['Computer Science', 'Mathematics'],
 'publicationTypes': ['JournalArticle'],
 'publicationDate': '2022-05-14',
 'authors': [{'authorId': '2145672500', 'name': 'Mengchu Li'},
  {'authorId': '10169073', 'name': 'Thomas B. Berrett'},
  {'authorId': '47111778', 'name': 'Yi Yu'}]}

In [ ]:
# merge the three new csv, on paper title and doi